### ISSUE TITLE
Add new rust pre-commit local hooks again

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/sadikkuzu.rs#2]
https://github.com/sadikkuzu/sadikkuzu.rs/commit/88bfb6c5751594e0154f380bef9b79e3afa78a58

https://pre-commit.ci/#configuration-skip

```yaml
ci:
    skip: [cargo-check, clippy]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-toml
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo-fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: rust
        types: [rust]
        args: ["--"]
    -   id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: rust
        types: [rust]
        pass_filenames: false
    -   id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: rust
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
```
